### ISSUE TITLE
Não deixa digitar o usuário.

### ISSUE THREAD

**Issue by michelalbonico** [Aulas-UTFPR/ES012022-exemplo#1]
Quando entro na página de login, o campo usuário aparece desabilitado.

**Comment by michelalbonico** [comment]
Não consegui reproduzir o bug. Por favor, seja mais específico.

**Comment by gustavoradin** [comment]
salve

**Comment by JulianeAdamy** [comment]
Tentando...

**Comment by joaovansan** [comment]
Teste.

**Comment by michelalbonico** [comment]
Problema resolvido,
